server:
  port: 9003
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/
feign:
  hystrix:
    enabled: false
ribbon:
  ReadTimeout: 11000
  ConnectTimeout: 10000
spring:
  application:
    name: client-api
  jackson:
    default-property-inclusion: NON_NULL
    date-format: yyyy-MM-dd HH:mm:ss
    timeZone: GMT+8
    serialization:
      WRITE_NULL_MAP_VALUES: false
      INDENT_OUTPUT: true